/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedDashboardImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedUsersIndexImport } from './routes/_authenticated.users.index'
import { Route as AuthenticatedSettingsIndexImport } from './routes/_authenticated.settings.index'
import { Route as AuthenticatedProductsIndexImport } from './routes/_authenticated.products.index'
import { Route as AuthenticatedUsersUserIdImport } from './routes/_authenticated.users.$userId'
import { Route as AuthenticatedSettingsRoomsImport } from './routes/_authenticated.settings.rooms'
import { Route as AuthenticatedSettingsIntegrationsImport } from './routes/_authenticated.settings.integrations'
import { Route as AuthenticatedSettingsImagesImport } from './routes/_authenticated.settings.images'
import { Route as AuthenticatedSettingsRoomsRoomIdIndexImport } from './routes/_authenticated.settings_.rooms.$roomId.index'
import { Route as AuthenticatedSettingsRoomsRoomIdProductIdIndexImport } from './routes/_authenticated.settings_.rooms.$roomId.$productId.index'

// Create Virtual Routes

const AuthenticatedUsersLazyImport = createFileRoute('/_authenticated/users')()
const AuthenticatedSettingsLazyImport = createFileRoute(
  '/_authenticated/settings',
)()
const AuthenticatedProductsLazyImport = createFileRoute(
  '/_authenticated/products',
)()
const AuthenticatedSettingsRoomsRoomIdLazyImport = createFileRoute(
  '/_authenticated/settings/rooms/$roomId',
)()
const AuthenticatedSettingsRoomsRoomIdProductIdLazyImport = createFileRoute(
  '/_authenticated/settings/rooms/$roomId/$productId',
)()

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedUsersLazyRoute = AuthenticatedUsersLazyImport.update({
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated.users.lazy').then((d) => d.Route),
)

const AuthenticatedSettingsLazyRoute = AuthenticatedSettingsLazyImport.update({
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated.settings.lazy').then((d) => d.Route),
)

const AuthenticatedProductsLazyRoute = AuthenticatedProductsLazyImport.update({
  path: '/products',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated.products.lazy').then((d) => d.Route),
)

const AuthenticatedDashboardRoute = AuthenticatedDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexImport.update({
  path: '/',
  getParentRoute: () => AuthenticatedUsersLazyRoute,
} as any)

const AuthenticatedSettingsIndexRoute = AuthenticatedSettingsIndexImport.update(
  {
    path: '/',
    getParentRoute: () => AuthenticatedSettingsLazyRoute,
  } as any,
)

const AuthenticatedProductsIndexRoute = AuthenticatedProductsIndexImport.update(
  {
    path: '/',
    getParentRoute: () => AuthenticatedProductsLazyRoute,
  } as any,
)

const AuthenticatedUsersUserIdRoute = AuthenticatedUsersUserIdImport.update({
  path: '/$userId',
  getParentRoute: () => AuthenticatedUsersLazyRoute,
} as any)

const AuthenticatedSettingsRoomsRoute = AuthenticatedSettingsRoomsImport.update(
  {
    path: '/rooms',
    getParentRoute: () => AuthenticatedSettingsLazyRoute,
  } as any,
)

const AuthenticatedSettingsIntegrationsRoute =
  AuthenticatedSettingsIntegrationsImport.update({
    path: '/integrations',
    getParentRoute: () => AuthenticatedSettingsLazyRoute,
  } as any)

const AuthenticatedSettingsImagesRoute =
  AuthenticatedSettingsImagesImport.update({
    path: '/images',
    getParentRoute: () => AuthenticatedSettingsLazyRoute,
  } as any)

const AuthenticatedSettingsRoomsRoomIdLazyRoute =
  AuthenticatedSettingsRoomsRoomIdLazyImport.update({
    path: '/settings/rooms/$roomId',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.settings_.rooms.$roomId.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsRoomsRoomIdIndexRoute =
  AuthenticatedSettingsRoomsRoomIdIndexImport.update({
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoomsRoomIdLazyRoute,
  } as any)

const AuthenticatedSettingsRoomsRoomIdProductIdLazyRoute =
  AuthenticatedSettingsRoomsRoomIdProductIdLazyImport.update({
    path: '/$productId',
    getParentRoute: () => AuthenticatedSettingsRoomsRoomIdLazyRoute,
  } as any).lazy(() =>
    import(
      './routes/_authenticated.settings_.rooms.$roomId.$productId.lazy'
    ).then((d) => d.Route),
  )

const AuthenticatedSettingsRoomsRoomIdProductIdIndexRoute =
  AuthenticatedSettingsRoomsRoomIdProductIdIndexImport.update({
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoomsRoomIdProductIdLazyRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/settings/images': {
      id: '/_authenticated/settings/images'
      path: '/images'
      fullPath: '/settings/images'
      preLoaderRoute: typeof AuthenticatedSettingsImagesImport
      parentRoute: typeof AuthenticatedSettingsLazyImport
    }
    '/_authenticated/settings/integrations': {
      id: '/_authenticated/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsImport
      parentRoute: typeof AuthenticatedSettingsLazyImport
    }
    '/_authenticated/settings/rooms': {
      id: '/_authenticated/settings/rooms'
      path: '/rooms'
      fullPath: '/settings/rooms'
      preLoaderRoute: typeof AuthenticatedSettingsRoomsImport
      parentRoute: typeof AuthenticatedSettingsLazyImport
    }
    '/_authenticated/users/$userId': {
      id: '/_authenticated/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthenticatedUsersUserIdImport
      parentRoute: typeof AuthenticatedUsersLazyImport
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexImport
      parentRoute: typeof AuthenticatedProductsLazyImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexImport
      parentRoute: typeof AuthenticatedSettingsLazyImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexImport
      parentRoute: typeof AuthenticatedUsersLazyImport
    }
    '/_authenticated/settings/rooms/$roomId': {
      id: '/_authenticated/settings/rooms/$roomId'
      path: '/settings/rooms/$roomId'
      fullPath: '/settings/rooms/$roomId'
      preLoaderRoute: typeof AuthenticatedSettingsRoomsRoomIdLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/settings/rooms/$roomId/$productId': {
      id: '/_authenticated/settings/rooms/$roomId/$productId'
      path: '/$productId'
      fullPath: '/settings/rooms/$roomId/$productId'
      preLoaderRoute: typeof AuthenticatedSettingsRoomsRoomIdProductIdLazyImport
      parentRoute: typeof AuthenticatedSettingsRoomsRoomIdLazyImport
    }
    '/_authenticated/settings/rooms/$roomId/': {
      id: '/_authenticated/settings/rooms/$roomId/'
      path: '/'
      fullPath: '/settings/rooms/$roomId/'
      preLoaderRoute: typeof AuthenticatedSettingsRoomsRoomIdIndexImport
      parentRoute: typeof AuthenticatedSettingsRoomsRoomIdLazyImport
    }
    '/_authenticated/settings/rooms/$roomId/$productId/': {
      id: '/_authenticated/settings/rooms/$roomId/$productId/'
      path: '/'
      fullPath: '/settings/rooms/$roomId/$productId/'
      preLoaderRoute: typeof AuthenticatedSettingsRoomsRoomIdProductIdIndexImport
      parentRoute: typeof AuthenticatedSettingsRoomsRoomIdProductIdLazyImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AuthenticatedRoute: AuthenticatedRoute.addChildren({
    AuthenticatedDashboardRoute,
    AuthenticatedProductsLazyRoute: AuthenticatedProductsLazyRoute.addChildren({
      AuthenticatedProductsIndexRoute,
    }),
    AuthenticatedSettingsLazyRoute: AuthenticatedSettingsLazyRoute.addChildren({
      AuthenticatedSettingsImagesRoute,
      AuthenticatedSettingsIntegrationsRoute,
      AuthenticatedSettingsRoomsRoute,
      AuthenticatedSettingsIndexRoute,
    }),
    AuthenticatedUsersLazyRoute: AuthenticatedUsersLazyRoute.addChildren({
      AuthenticatedUsersUserIdRoute,
      AuthenticatedUsersIndexRoute,
    }),
    AuthenticatedSettingsRoomsRoomIdLazyRoute:
      AuthenticatedSettingsRoomsRoomIdLazyRoute.addChildren({
        AuthenticatedSettingsRoomsRoomIdProductIdLazyRoute:
          AuthenticatedSettingsRoomsRoomIdProductIdLazyRoute.addChildren({
            AuthenticatedSettingsRoomsRoomIdProductIdIndexRoute,
          }),
        AuthenticatedSettingsRoomsRoomIdIndexRoute,
      }),
  }),
  LoginRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/login"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/dashboard",
        "/_authenticated/products",
        "/_authenticated/settings",
        "/_authenticated/users",
        "/_authenticated/settings/rooms/$roomId"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_authenticated/dashboard": {
      "filePath": "_authenticated.dashboard.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/products": {
      "filePath": "_authenticated.products.lazy.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/products/"
      ]
    },
    "/_authenticated/settings": {
      "filePath": "_authenticated.settings.lazy.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/settings/images",
        "/_authenticated/settings/integrations",
        "/_authenticated/settings/rooms",
        "/_authenticated/settings/"
      ]
    },
    "/_authenticated/users": {
      "filePath": "_authenticated.users.lazy.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/users/$userId",
        "/_authenticated/users/"
      ]
    },
    "/_authenticated/settings/images": {
      "filePath": "_authenticated.settings.images.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/integrations": {
      "filePath": "_authenticated.settings.integrations.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/rooms": {
      "filePath": "_authenticated.settings.rooms.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/users/$userId": {
      "filePath": "_authenticated.users.$userId.tsx",
      "parent": "/_authenticated/users"
    },
    "/_authenticated/products/": {
      "filePath": "_authenticated.products.index.tsx",
      "parent": "/_authenticated/products"
    },
    "/_authenticated/settings/": {
      "filePath": "_authenticated.settings.index.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/users/": {
      "filePath": "_authenticated.users.index.tsx",
      "parent": "/_authenticated/users"
    },
    "/_authenticated/settings/rooms/$roomId": {
      "filePath": "_authenticated.settings_.rooms.$roomId.lazy.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/settings/rooms/$roomId/$productId",
        "/_authenticated/settings/rooms/$roomId/"
      ]
    },
    "/_authenticated/settings/rooms/$roomId/$productId": {
      "filePath": "_authenticated.settings_.rooms.$roomId.$productId.lazy.tsx",
      "parent": "/_authenticated/settings/rooms/$roomId",
      "children": [
        "/_authenticated/settings/rooms/$roomId/$productId/"
      ]
    },
    "/_authenticated/settings/rooms/$roomId/": {
      "filePath": "_authenticated.settings_.rooms.$roomId.index.tsx",
      "parent": "/_authenticated/settings/rooms/$roomId"
    },
    "/_authenticated/settings/rooms/$roomId/$productId/": {
      "filePath": "_authenticated.settings_.rooms.$roomId.$productId.index.tsx",
      "parent": "/_authenticated/settings/rooms/$roomId/$productId"
    }
  }
}
ROUTE_MANIFEST_END */
