/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedDashboardImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedUsersIndexImport } from './routes/_authenticated.users.index'
import { Route as AuthenticatedSettingsIndexImport } from './routes/_authenticated.settings.index'
import { Route as AuthenticatedProductsIndexImport } from './routes/_authenticated.products.index'
import { Route as AuthenticatedUsersUserIdImport } from './routes/_authenticated.users.$userId'
import { Route as AuthenticatedSettingsRoomsImport } from './routes/_authenticated.settings.rooms'
import { Route as AuthenticatedSettingsIntegrationsImport } from './routes/_authenticated.settings.integrations'
import { Route as AuthenticatedSettingsImagesImport } from './routes/_authenticated.settings.images'
import { Route as AuthenticatedSettingsRoomsRoomIdIndexImport } from './routes/_authenticated.settings_.rooms.$roomId.index'
import { Route as AuthenticatedSettingsRoomsRoomIdProductsImport } from './routes/_authenticated.settings_.rooms.$roomId.products'
import { Route as AuthenticatedSettingsRoomsRoomIdCostScriptsImport } from './routes/_authenticated.settings_.rooms.$roomId.cost-scripts'
import { Route as AuthenticatedSettingsRoomsRoomIdConfigurationImport } from './routes/_authenticated.settings_.rooms.$roomId.configuration'
import { Route as AuthenticatedSettingsRoomsRoomIdProductsProductIdIndexImport } from './routes/_authenticated.settings_.rooms.$roomId_.products.$productId.index'

// Create Virtual Routes

const AuthenticatedUsersLazyImport = createFileRoute('/_authenticated/users')()
const AuthenticatedSettingsLazyImport = createFileRoute(
  '/_authenticated/settings',
)()
const AuthenticatedProductsLazyImport = createFileRoute(
  '/_authenticated/products',
)()
const AuthenticatedSettingsRoomsRoomIdLazyImport = createFileRoute(
  '/_authenticated/settings/rooms/$roomId',
)()
const AuthenticatedSettingsRoomsRoomIdProductsProductIdLazyImport =
  createFileRoute(
    '/_authenticated/settings/rooms/$roomId/products/$productId',
  )()

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedUsersLazyRoute = AuthenticatedUsersLazyImport.update({
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated.users.lazy').then((d) => d.Route),
)

const AuthenticatedSettingsLazyRoute = AuthenticatedSettingsLazyImport.update({
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated.settings.lazy').then((d) => d.Route),
)

const AuthenticatedProductsLazyRoute = AuthenticatedProductsLazyImport.update({
  path: '/products',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated.products.lazy').then((d) => d.Route),
)

const AuthenticatedDashboardRoute = AuthenticatedDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexImport.update({
  path: '/',
  getParentRoute: () => AuthenticatedUsersLazyRoute,
} as any)

const AuthenticatedSettingsIndexRoute = AuthenticatedSettingsIndexImport.update(
  {
    path: '/',
    getParentRoute: () => AuthenticatedSettingsLazyRoute,
  } as any,
)

const AuthenticatedProductsIndexRoute = AuthenticatedProductsIndexImport.update(
  {
    path: '/',
    getParentRoute: () => AuthenticatedProductsLazyRoute,
  } as any,
)

const AuthenticatedUsersUserIdRoute = AuthenticatedUsersUserIdImport.update({
  path: '/$userId',
  getParentRoute: () => AuthenticatedUsersLazyRoute,
} as any)

const AuthenticatedSettingsRoomsRoute = AuthenticatedSettingsRoomsImport.update(
  {
    path: '/rooms',
    getParentRoute: () => AuthenticatedSettingsLazyRoute,
  } as any,
)

const AuthenticatedSettingsIntegrationsRoute =
  AuthenticatedSettingsIntegrationsImport.update({
    path: '/integrations',
    getParentRoute: () => AuthenticatedSettingsLazyRoute,
  } as any)

const AuthenticatedSettingsImagesRoute =
  AuthenticatedSettingsImagesImport.update({
    path: '/images',
    getParentRoute: () => AuthenticatedSettingsLazyRoute,
  } as any)

const AuthenticatedSettingsRoomsRoomIdLazyRoute =
  AuthenticatedSettingsRoomsRoomIdLazyImport.update({
    path: '/settings/rooms/$roomId',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.settings_.rooms.$roomId.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsRoomsRoomIdIndexRoute =
  AuthenticatedSettingsRoomsRoomIdIndexImport.update({
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoomsRoomIdLazyRoute,
  } as any)

const AuthenticatedSettingsRoomsRoomIdProductsRoute =
  AuthenticatedSettingsRoomsRoomIdProductsImport.update({
    path: '/products',
    getParentRoute: () => AuthenticatedSettingsRoomsRoomIdLazyRoute,
  } as any)

const AuthenticatedSettingsRoomsRoomIdCostScriptsRoute =
  AuthenticatedSettingsRoomsRoomIdCostScriptsImport.update({
    path: '/cost-scripts',
    getParentRoute: () => AuthenticatedSettingsRoomsRoomIdLazyRoute,
  } as any)

const AuthenticatedSettingsRoomsRoomIdConfigurationRoute =
  AuthenticatedSettingsRoomsRoomIdConfigurationImport.update({
    path: '/configuration',
    getParentRoute: () => AuthenticatedSettingsRoomsRoomIdLazyRoute,
  } as any)

const AuthenticatedSettingsRoomsRoomIdProductsProductIdLazyRoute =
  AuthenticatedSettingsRoomsRoomIdProductsProductIdLazyImport.update({
    path: '/settings/rooms/$roomId/products/$productId',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import(
      './routes/_authenticated.settings_.rooms.$roomId_.products.$productId.lazy'
    ).then((d) => d.Route),
  )

const AuthenticatedSettingsRoomsRoomIdProductsProductIdIndexRoute =
  AuthenticatedSettingsRoomsRoomIdProductsProductIdIndexImport.update({
    path: '/',
    getParentRoute: () =>
      AuthenticatedSettingsRoomsRoomIdProductsProductIdLazyRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/settings/images': {
      id: '/_authenticated/settings/images'
      path: '/images'
      fullPath: '/settings/images'
      preLoaderRoute: typeof AuthenticatedSettingsImagesImport
      parentRoute: typeof AuthenticatedSettingsLazyImport
    }
    '/_authenticated/settings/integrations': {
      id: '/_authenticated/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsImport
      parentRoute: typeof AuthenticatedSettingsLazyImport
    }
    '/_authenticated/settings/rooms': {
      id: '/_authenticated/settings/rooms'
      path: '/rooms'
      fullPath: '/settings/rooms'
      preLoaderRoute: typeof AuthenticatedSettingsRoomsImport
      parentRoute: typeof AuthenticatedSettingsLazyImport
    }
    '/_authenticated/users/$userId': {
      id: '/_authenticated/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthenticatedUsersUserIdImport
      parentRoute: typeof AuthenticatedUsersLazyImport
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexImport
      parentRoute: typeof AuthenticatedProductsLazyImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexImport
      parentRoute: typeof AuthenticatedSettingsLazyImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexImport
      parentRoute: typeof AuthenticatedUsersLazyImport
    }
    '/_authenticated/settings/rooms/$roomId': {
      id: '/_authenticated/settings/rooms/$roomId'
      path: '/settings/rooms/$roomId'
      fullPath: '/settings/rooms/$roomId'
      preLoaderRoute: typeof AuthenticatedSettingsRoomsRoomIdLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/settings/rooms/$roomId/configuration': {
      id: '/_authenticated/settings/rooms/$roomId/configuration'
      path: '/configuration'
      fullPath: '/settings/rooms/$roomId/configuration'
      preLoaderRoute: typeof AuthenticatedSettingsRoomsRoomIdConfigurationImport
      parentRoute: typeof AuthenticatedSettingsRoomsRoomIdLazyImport
    }
    '/_authenticated/settings/rooms/$roomId/cost-scripts': {
      id: '/_authenticated/settings/rooms/$roomId/cost-scripts'
      path: '/cost-scripts'
      fullPath: '/settings/rooms/$roomId/cost-scripts'
      preLoaderRoute: typeof AuthenticatedSettingsRoomsRoomIdCostScriptsImport
      parentRoute: typeof AuthenticatedSettingsRoomsRoomIdLazyImport
    }
    '/_authenticated/settings/rooms/$roomId/products': {
      id: '/_authenticated/settings/rooms/$roomId/products'
      path: '/products'
      fullPath: '/settings/rooms/$roomId/products'
      preLoaderRoute: typeof AuthenticatedSettingsRoomsRoomIdProductsImport
      parentRoute: typeof AuthenticatedSettingsRoomsRoomIdLazyImport
    }
    '/_authenticated/settings/rooms/$roomId/': {
      id: '/_authenticated/settings/rooms/$roomId/'
      path: '/'
      fullPath: '/settings/rooms/$roomId/'
      preLoaderRoute: typeof AuthenticatedSettingsRoomsRoomIdIndexImport
      parentRoute: typeof AuthenticatedSettingsRoomsRoomIdLazyImport
    }
    '/_authenticated/settings/rooms/$roomId/products/$productId': {
      id: '/_authenticated/settings/rooms/$roomId/products/$productId'
      path: '/settings/rooms/$roomId/products/$productId'
      fullPath: '/settings/rooms/$roomId/products/$productId'
      preLoaderRoute: typeof AuthenticatedSettingsRoomsRoomIdProductsProductIdLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/settings/rooms/$roomId/products/$productId/': {
      id: '/_authenticated/settings/rooms/$roomId/products/$productId/'
      path: '/'
      fullPath: '/settings/rooms/$roomId/products/$productId/'
      preLoaderRoute: typeof AuthenticatedSettingsRoomsRoomIdProductsProductIdIndexImport
      parentRoute: typeof AuthenticatedSettingsRoomsRoomIdProductsProductIdLazyImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedProductsLazyRouteChildren {
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
}

const AuthenticatedProductsLazyRouteChildren: AuthenticatedProductsLazyRouteChildren =
  {
    AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  }

const AuthenticatedProductsLazyRouteWithChildren =
  AuthenticatedProductsLazyRoute._addFileChildren(
    AuthenticatedProductsLazyRouteChildren,
  )

interface AuthenticatedSettingsLazyRouteChildren {
  AuthenticatedSettingsImagesRoute: typeof AuthenticatedSettingsImagesRoute
  AuthenticatedSettingsIntegrationsRoute: typeof AuthenticatedSettingsIntegrationsRoute
  AuthenticatedSettingsRoomsRoute: typeof AuthenticatedSettingsRoomsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsLazyRouteChildren: AuthenticatedSettingsLazyRouteChildren =
  {
    AuthenticatedSettingsImagesRoute: AuthenticatedSettingsImagesRoute,
    AuthenticatedSettingsIntegrationsRoute:
      AuthenticatedSettingsIntegrationsRoute,
    AuthenticatedSettingsRoomsRoute: AuthenticatedSettingsRoomsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsLazyRouteWithChildren =
  AuthenticatedSettingsLazyRoute._addFileChildren(
    AuthenticatedSettingsLazyRouteChildren,
  )

interface AuthenticatedUsersLazyRouteChildren {
  AuthenticatedUsersUserIdRoute: typeof AuthenticatedUsersUserIdRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedUsersLazyRouteChildren: AuthenticatedUsersLazyRouteChildren =
  {
    AuthenticatedUsersUserIdRoute: AuthenticatedUsersUserIdRoute,
    AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  }

const AuthenticatedUsersLazyRouteWithChildren =
  AuthenticatedUsersLazyRoute._addFileChildren(
    AuthenticatedUsersLazyRouteChildren,
  )

interface AuthenticatedSettingsRoomsRoomIdLazyRouteChildren {
  AuthenticatedSettingsRoomsRoomIdConfigurationRoute: typeof AuthenticatedSettingsRoomsRoomIdConfigurationRoute
  AuthenticatedSettingsRoomsRoomIdCostScriptsRoute: typeof AuthenticatedSettingsRoomsRoomIdCostScriptsRoute
  AuthenticatedSettingsRoomsRoomIdProductsRoute: typeof AuthenticatedSettingsRoomsRoomIdProductsRoute
  AuthenticatedSettingsRoomsRoomIdIndexRoute: typeof AuthenticatedSettingsRoomsRoomIdIndexRoute
}

const AuthenticatedSettingsRoomsRoomIdLazyRouteChildren: AuthenticatedSettingsRoomsRoomIdLazyRouteChildren =
  {
    AuthenticatedSettingsRoomsRoomIdConfigurationRoute:
      AuthenticatedSettingsRoomsRoomIdConfigurationRoute,
    AuthenticatedSettingsRoomsRoomIdCostScriptsRoute:
      AuthenticatedSettingsRoomsRoomIdCostScriptsRoute,
    AuthenticatedSettingsRoomsRoomIdProductsRoute:
      AuthenticatedSettingsRoomsRoomIdProductsRoute,
    AuthenticatedSettingsRoomsRoomIdIndexRoute:
      AuthenticatedSettingsRoomsRoomIdIndexRoute,
  }

const AuthenticatedSettingsRoomsRoomIdLazyRouteWithChildren =
  AuthenticatedSettingsRoomsRoomIdLazyRoute._addFileChildren(
    AuthenticatedSettingsRoomsRoomIdLazyRouteChildren,
  )

interface AuthenticatedSettingsRoomsRoomIdProductsProductIdLazyRouteChildren {
  AuthenticatedSettingsRoomsRoomIdProductsProductIdIndexRoute: typeof AuthenticatedSettingsRoomsRoomIdProductsProductIdIndexRoute
}

const AuthenticatedSettingsRoomsRoomIdProductsProductIdLazyRouteChildren: AuthenticatedSettingsRoomsRoomIdProductsProductIdLazyRouteChildren =
  {
    AuthenticatedSettingsRoomsRoomIdProductsProductIdIndexRoute:
      AuthenticatedSettingsRoomsRoomIdProductsProductIdIndexRoute,
  }

const AuthenticatedSettingsRoomsRoomIdProductsProductIdLazyRouteWithChildren =
  AuthenticatedSettingsRoomsRoomIdProductsProductIdLazyRoute._addFileChildren(
    AuthenticatedSettingsRoomsRoomIdProductsProductIdLazyRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProductsLazyRoute: typeof AuthenticatedProductsLazyRouteWithChildren
  AuthenticatedSettingsLazyRoute: typeof AuthenticatedSettingsLazyRouteWithChildren
  AuthenticatedUsersLazyRoute: typeof AuthenticatedUsersLazyRouteWithChildren
  AuthenticatedSettingsRoomsRoomIdLazyRoute: typeof AuthenticatedSettingsRoomsRoomIdLazyRouteWithChildren
  AuthenticatedSettingsRoomsRoomIdProductsProductIdLazyRoute: typeof AuthenticatedSettingsRoomsRoomIdProductsProductIdLazyRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProductsLazyRoute: AuthenticatedProductsLazyRouteWithChildren,
  AuthenticatedSettingsLazyRoute: AuthenticatedSettingsLazyRouteWithChildren,
  AuthenticatedUsersLazyRoute: AuthenticatedUsersLazyRouteWithChildren,
  AuthenticatedSettingsRoomsRoomIdLazyRoute:
    AuthenticatedSettingsRoomsRoomIdLazyRouteWithChildren,
  AuthenticatedSettingsRoomsRoomIdProductsProductIdLazyRoute:
    AuthenticatedSettingsRoomsRoomIdProductsProductIdLazyRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/products': typeof AuthenticatedProductsLazyRouteWithChildren
  '/settings': typeof AuthenticatedSettingsLazyRouteWithChildren
  '/users': typeof AuthenticatedUsersLazyRouteWithChildren
  '/settings/images': typeof AuthenticatedSettingsImagesRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/rooms': typeof AuthenticatedSettingsRoomsRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/settings/rooms/$roomId': typeof AuthenticatedSettingsRoomsRoomIdLazyRouteWithChildren
  '/settings/rooms/$roomId/configuration': typeof AuthenticatedSettingsRoomsRoomIdConfigurationRoute
  '/settings/rooms/$roomId/cost-scripts': typeof AuthenticatedSettingsRoomsRoomIdCostScriptsRoute
  '/settings/rooms/$roomId/products': typeof AuthenticatedSettingsRoomsRoomIdProductsRoute
  '/settings/rooms/$roomId/': typeof AuthenticatedSettingsRoomsRoomIdIndexRoute
  '/settings/rooms/$roomId/products/$productId': typeof AuthenticatedSettingsRoomsRoomIdProductsProductIdLazyRouteWithChildren
  '/settings/rooms/$roomId/products/$productId/': typeof AuthenticatedSettingsRoomsRoomIdProductsProductIdIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings/images': typeof AuthenticatedSettingsImagesRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/rooms': typeof AuthenticatedSettingsRoomsRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/settings/rooms/$roomId/configuration': typeof AuthenticatedSettingsRoomsRoomIdConfigurationRoute
  '/settings/rooms/$roomId/cost-scripts': typeof AuthenticatedSettingsRoomsRoomIdCostScriptsRoute
  '/settings/rooms/$roomId/products': typeof AuthenticatedSettingsRoomsRoomIdProductsRoute
  '/settings/rooms/$roomId': typeof AuthenticatedSettingsRoomsRoomIdIndexRoute
  '/settings/rooms/$roomId/products/$productId': typeof AuthenticatedSettingsRoomsRoomIdProductsProductIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/products': typeof AuthenticatedProductsLazyRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsLazyRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersLazyRouteWithChildren
  '/_authenticated/settings/images': typeof AuthenticatedSettingsImagesRoute
  '/_authenticated/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/_authenticated/settings/rooms': typeof AuthenticatedSettingsRoomsRoute
  '/_authenticated/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/settings/rooms/$roomId': typeof AuthenticatedSettingsRoomsRoomIdLazyRouteWithChildren
  '/_authenticated/settings/rooms/$roomId/configuration': typeof AuthenticatedSettingsRoomsRoomIdConfigurationRoute
  '/_authenticated/settings/rooms/$roomId/cost-scripts': typeof AuthenticatedSettingsRoomsRoomIdCostScriptsRoute
  '/_authenticated/settings/rooms/$roomId/products': typeof AuthenticatedSettingsRoomsRoomIdProductsRoute
  '/_authenticated/settings/rooms/$roomId/': typeof AuthenticatedSettingsRoomsRoomIdIndexRoute
  '/_authenticated/settings/rooms/$roomId/products/$productId': typeof AuthenticatedSettingsRoomsRoomIdProductsProductIdLazyRouteWithChildren
  '/_authenticated/settings/rooms/$roomId/products/$productId/': typeof AuthenticatedSettingsRoomsRoomIdProductsProductIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/dashboard'
    | '/products'
    | '/settings'
    | '/users'
    | '/settings/images'
    | '/settings/integrations'
    | '/settings/rooms'
    | '/users/$userId'
    | '/products/'
    | '/settings/'
    | '/users/'
    | '/settings/rooms/$roomId'
    | '/settings/rooms/$roomId/configuration'
    | '/settings/rooms/$roomId/cost-scripts'
    | '/settings/rooms/$roomId/products'
    | '/settings/rooms/$roomId/'
    | '/settings/rooms/$roomId/products/$productId'
    | '/settings/rooms/$roomId/products/$productId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/login'
    | '/dashboard'
    | '/settings/images'
    | '/settings/integrations'
    | '/settings/rooms'
    | '/users/$userId'
    | '/products'
    | '/settings'
    | '/users'
    | '/settings/rooms/$roomId/configuration'
    | '/settings/rooms/$roomId/cost-scripts'
    | '/settings/rooms/$roomId/products'
    | '/settings/rooms/$roomId'
    | '/settings/rooms/$roomId/products/$productId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/products'
    | '/_authenticated/settings'
    | '/_authenticated/users'
    | '/_authenticated/settings/images'
    | '/_authenticated/settings/integrations'
    | '/_authenticated/settings/rooms'
    | '/_authenticated/users/$userId'
    | '/_authenticated/products/'
    | '/_authenticated/settings/'
    | '/_authenticated/users/'
    | '/_authenticated/settings/rooms/$roomId'
    | '/_authenticated/settings/rooms/$roomId/configuration'
    | '/_authenticated/settings/rooms/$roomId/cost-scripts'
    | '/_authenticated/settings/rooms/$roomId/products'
    | '/_authenticated/settings/rooms/$roomId/'
    | '/_authenticated/settings/rooms/$roomId/products/$productId'
    | '/_authenticated/settings/rooms/$roomId/products/$productId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/login"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/dashboard",
        "/_authenticated/products",
        "/_authenticated/settings",
        "/_authenticated/users",
        "/_authenticated/settings/rooms/$roomId",
        "/_authenticated/settings/rooms/$roomId/products/$productId"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_authenticated/dashboard": {
      "filePath": "_authenticated.dashboard.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/products": {
      "filePath": "_authenticated.products.lazy.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/products/"
      ]
    },
    "/_authenticated/settings": {
      "filePath": "_authenticated.settings.lazy.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/settings/images",
        "/_authenticated/settings/integrations",
        "/_authenticated/settings/rooms",
        "/_authenticated/settings/"
      ]
    },
    "/_authenticated/users": {
      "filePath": "_authenticated.users.lazy.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/users/$userId",
        "/_authenticated/users/"
      ]
    },
    "/_authenticated/settings/images": {
      "filePath": "_authenticated.settings.images.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/integrations": {
      "filePath": "_authenticated.settings.integrations.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/rooms": {
      "filePath": "_authenticated.settings.rooms.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/users/$userId": {
      "filePath": "_authenticated.users.$userId.tsx",
      "parent": "/_authenticated/users"
    },
    "/_authenticated/products/": {
      "filePath": "_authenticated.products.index.tsx",
      "parent": "/_authenticated/products"
    },
    "/_authenticated/settings/": {
      "filePath": "_authenticated.settings.index.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/users/": {
      "filePath": "_authenticated.users.index.tsx",
      "parent": "/_authenticated/users"
    },
    "/_authenticated/settings/rooms/$roomId": {
      "filePath": "_authenticated.settings_.rooms.$roomId.lazy.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/settings/rooms/$roomId/configuration",
        "/_authenticated/settings/rooms/$roomId/cost-scripts",
        "/_authenticated/settings/rooms/$roomId/products",
        "/_authenticated/settings/rooms/$roomId/"
      ]
    },
    "/_authenticated/settings/rooms/$roomId/configuration": {
      "filePath": "_authenticated.settings_.rooms.$roomId.configuration.tsx",
      "parent": "/_authenticated/settings/rooms/$roomId"
    },
    "/_authenticated/settings/rooms/$roomId/cost-scripts": {
      "filePath": "_authenticated.settings_.rooms.$roomId.cost-scripts.tsx",
      "parent": "/_authenticated/settings/rooms/$roomId"
    },
    "/_authenticated/settings/rooms/$roomId/products": {
      "filePath": "_authenticated.settings_.rooms.$roomId.products.tsx",
      "parent": "/_authenticated/settings/rooms/$roomId"
    },
    "/_authenticated/settings/rooms/$roomId/": {
      "filePath": "_authenticated.settings_.rooms.$roomId.index.tsx",
      "parent": "/_authenticated/settings/rooms/$roomId"
    },
    "/_authenticated/settings/rooms/$roomId/products/$productId": {
      "filePath": "_authenticated.settings_.rooms.$roomId_.products.$productId.lazy.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/settings/rooms/$roomId/products/$productId/"
      ]
    },
    "/_authenticated/settings/rooms/$roomId/products/$productId/": {
      "filePath": "_authenticated.settings_.rooms.$roomId_.products.$productId.index.tsx",
      "parent": "/_authenticated/settings/rooms/$roomId/products/$productId"
    }
  }
}
ROUTE_MANIFEST_END */
