/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "AssetsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Client": {
      "domain": string
      "isDev": boolean
      "realtimeUrl": string
      "replicacheLicenseKey": string
      "type": "sst.sst.Linkable"
    }
    "Db": {
      "postgres": {
        "url": string
      }
      "type": "sst.sst.Linkable"
    }
    "DocumentsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "GoogleClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "InfraBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Meta": {
      "app": {
        "name": string
        "stage": string
      }
      "domain": string
      "isDev": boolean
      "type": "sst.sst.Linkable"
    }
    "Oauth2": {
      "entraId": {
        "clientId": string
        "clientSecret": string
      }
      "google": {
        "clientId": string
        "clientSecret": string
      }
      "type": "sst.sst.Linkable"
    }
    "PartyKitUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Realtime": {
      "apiKey": string
      "type": "sst.sst.Linkable"
      "url": string
    }
    "ReplicacheLicenseKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ReverseProxy": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "Storage": {
      "assets": {
        "bucket": string
        "distribution": {
          "domain": string
          "privateKey": string
          "publicKey": {
            "id": string
          }
        }
      }
      "documents": {
        "bucket": string
      }
      "infra": {
        "bucket": string
      }
      "type": "sst.sst.Linkable"
    }
    "Web": {
      "type": "sst.aws.Astro"
      "url": string
    }
  }
}
