/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthedImport } from './routes/_authed'
import { Route as AuthedDashboardImport } from './routes/_authed.dashboard'
import { Route as AuthedSettingsIndexImport } from './routes/_authed.settings.index'
import { Route as AuthedSettingsPapercutImport } from './routes/_authed.settings.papercut'

// Create Virtual Routes

const AuthedUsersLazyImport = createFileRoute('/_authed/users')()
const AuthedSettingsLazyImport = createFileRoute('/_authed/settings')()

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const AuthedUsersLazyRoute = AuthedUsersLazyImport.update({
  path: '/users',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() => import('./routes/_authed.users.lazy').then((d) => d.Route))

const AuthedSettingsLazyRoute = AuthedSettingsLazyImport.update({
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed.settings.lazy').then((d) => d.Route),
)

const AuthedDashboardRoute = AuthedDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedSettingsIndexRoute = AuthedSettingsIndexImport.update({
  path: '/',
  getParentRoute: () => AuthedSettingsLazyRoute,
} as any)

const AuthedSettingsPapercutRoute = AuthedSettingsPapercutImport.update({
  path: '/papercut',
  getParentRoute: () => AuthedSettingsLazyRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsLazyImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/users': {
      id: '/_authed/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthedUsersLazyImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/settings/papercut': {
      id: '/_authed/settings/papercut'
      path: '/papercut'
      fullPath: '/settings/papercut'
      preLoaderRoute: typeof AuthedSettingsPapercutImport
      parentRoute: typeof AuthedSettingsLazyImport
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexImport
      parentRoute: typeof AuthedSettingsLazyImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AuthedRoute: AuthedRoute.addChildren({
    AuthedDashboardRoute,
    AuthedSettingsLazyRoute: AuthedSettingsLazyRoute.addChildren({
      AuthedSettingsPapercutRoute,
      AuthedSettingsIndexRoute,
    }),
    AuthedUsersLazyRoute,
  }),
  LoginRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authed",
        "/login"
      ]
    },
    "/_authed": {
      "filePath": "_authed.tsx",
      "children": [
        "/_authed/dashboard",
        "/_authed/settings",
        "/_authed/users"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_authed/dashboard": {
      "filePath": "_authed.dashboard.tsx",
      "parent": "/_authed"
    },
    "/_authed/settings": {
      "filePath": "_authed.settings.lazy.tsx",
      "parent": "/_authed",
      "children": [
        "/_authed/settings/papercut",
        "/_authed/settings/"
      ]
    },
    "/_authed/users": {
      "filePath": "_authed.users.lazy.tsx",
      "parent": "/_authed"
    },
    "/_authed/settings/papercut": {
      "filePath": "_authed.settings.papercut.tsx",
      "parent": "/_authed/settings"
    },
    "/_authed/settings/": {
      "filePath": "_authed.settings.index.tsx",
      "parent": "/_authed/settings"
    }
  }
}
ROUTE_MANIFEST_END */
