/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "AppData": {
      "domainName": {
        "fullyQualified": string
        "value": string
      }
      "isDev": boolean
      "name": string
      "stage": string
      "type": "sst.sst.Linkable"
    }
    "BootstrapRoleArn": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Client": {
      "appFqdn": string
      "isDev": boolean
      "realtimeUrl": string
      "replicacheLicenseKey": string
      "type": "sst.sst.Linkable"
    }
    "Cloud": {
      "aws": {
        "account": {
          "id": string
        }
        "organization": {
          "email": string
          "id": string
          "managementRole": {
            "arn": string
          }
          "tenantsOrganizationalUnit": {
            "id": string
          }
        }
        "region": string
        "tenantAccountAccessRole": {
          "name": string
        }
      }
      "cloudflare": {
        "apiToken": string
      }
      "type": "sst.sst.Linkable"
    }
    "Code": {
      "bucket": {
        "name": string
        "object": {
          "papercutSecureBridgeHandler": {
            "key": string
            "versionId": string
          }
          "tailscaleLayer": {
            "key": string
            "versionId": string
          }
        }
      }
      "type": "sst.sst.Linkable"
    }
    "CodeBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Db": {
      "postgres": {
        "url": string
      }
      "type": "sst.sst.Linkable"
    }
    "DomainName": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "InfraDeadLetterQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "Oauth2": {
      "entraId": {
        "clientId": string
        "clientSecret": string
      }
      "google": {
        "clientId": string
        "clientSecret": string
      }
      "type": "sst.sst.Linkable"
    }
    "PartyKitUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PulumiBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Realtime": {
      "apiKey": string
      "type": "sst.sst.Linkable"
      "url": string
    }
    "ReplicacheLicenseKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ReverseProxy": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "TenantInfraQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "Web": {
      "type": "sst.aws.Astro"
      "url": string
    }
    "WebOutputs": {
      "server": {
        "role": {
          "principal": string
        }
      }
      "type": "sst.sst.Linkable"
    }
    "WebPassword": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WebUsername": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
