[project]
name = "tenant-infra"
version = "0.1.0"
description = "Manage tenant infrastructure with the Pulumi Automation API"
requires-python = ">=3.11"
dependencies = [
    "aws-lambda-powertools>=3.0.0",
    "boto3-stubs[sts]>=1.35.26",
    "boto3>=1.35.26",
    "pulumi-aws>=6.52.0",
    "pulumi>=3.133.0",
    "requests>=2.32.3",
]
