#:schema node_modules/wrangler/config-schema.json
name = "paperwait-ip-rate-limiter"
main = "src/index.js"
compatibility_date = "2024-09-03"

# The rate limiting API is in open beta.
[[unsafe.bindings]]
name = "IP_RATE_LIMITER"
type = "ratelimit"
# An identifier you define, that is unique to your Cloudflare account.
# Must be an integer.
namespace_id = "1002"

# Limit: the number of tokens allowed within a given period in a single
# Cloudflare location
# Period: the duration of the period, in seconds. Must be either 10 or 60
simple = { limit = 5000, period = 60 }
